export const GET_PLANT_REQUEST = 'GET_PLANT_REQUEST';
export const GET_PLANT_SUCCESS = 'GET_PLANT_SUCCESS';
export const GET_PLANT_FAIL = 'GET_PLANT_FAIL';

export const GET_PLANT_DETAILS_REQUEST = 'GET_PLANT_DETAILS_REQUEST';
export const GET_PLANT_DETAILS_SUCCESS = 'GET_PLANT_DETAILS_SUCCESS';
export const GET_PLANT_DETAILS_FAIL = 'GET_PLANT_DETAILS_FAIL';
export const GET_PLANT_DETAILS_RESET = 'GET_PLANT_DETAILS_RESET';

export const PLANT_CREATE_REQUEST = 'PLANT_CREATE_REQUEST';
export const PLANT_CREATE_SUCCESS = 'PLANT_CREATE_SUCCESS';
export const PLANT_CREATE_FAIL = 'PLANT_CREATE_FAIL';
export const PLANT_CREATE_RESET = 'PLANT_CREATE_RESET';

export const PLANT_UPDATE_REQUEST = 'PLANT_UPDATE_REQUEST';
export const PLANT_UPDATE_SUCCESS = 'PLANT_UPDATE_SUCCESS';
export const PLANT_UPDATE_FAIL = 'PLANT_UPDATE_FAIL';
export const PLANT_UPDATE_RESET = 'PLANT_UPDATE_RESET';

export const PLANT_DELETE_REQUEST = 'PLANT_DELETE_REQUEST';
export const PLANT_DELETE_SUCCESS = 'PLANT_DELETE_SUCCESS';
export const PLANT_DELETE_FAIL = 'PLANT_DELETE_FAIL';
export const PLANT_DELETE_RESET = 'PLANT_DELETE_RESET';

export const PLANT_WATER_REQUEST = 'PLANT_WATER_REQUEST';
export const PLANT_WATER_SUCCESS = 'PLANT_WATER_SUCCESS';
export const PLANT_WATER_FAIL = 'PLANT_WATER_FAIL';
export const PLANT_WATER_RESET = 'PLANT_WATER_RESET';

export const PLANT_FERTILIZE_REQUEST = 'PLANT_FERTILIZE_REQUEST';
export const PLANT_FERTILIZE_SUCCESS = 'PLANT_FERTILIZE_SUCCESS';
export const PLANT_FERTILIZE_FAIL = 'PLANT_FERTILIZE_FAIL';
export const PLANT_FERTILIZE_RESET = 'PLANT_FERTILIZE_RESET';